const crypto = require('crypto');

module.exports = [
    { name: 'base64en', desc: 'Encode du texte clair en format Base64 brut.', usage: '.base64en <texte>', execute: async(ctx) => { if(!ctx.q) return await ctx.reply('Texte manquant'); await ctx.reply(`🔐 Base64: \n\`\`\`${Buffer.from(ctx.q).toString('base64')}\`\`\``) } },
    { name: 'base64de', desc: 'Décode une chaîne de caractères Base64 vers du texte lisible.', usage: '.base64de <base64>', execute: async(ctx) => { if(!ctx.q) return await ctx.reply('Texte manquant'); await ctx.reply(`🔓 Texte: \n\`\`\`${Buffer.from(ctx.q, 'base64').toString('utf8')}\`\`\``) } },
    { name: 'hexen', desc: 'Encode du texte classique en format Hexadécimal.', usage: '.hexen <texte>', execute: async(ctx) => { if(!ctx.q) return await ctx.reply('Texte manquant'); await ctx.reply(`🔐 Hex: \n\`\`\`${Buffer.from(ctx.q).toString('hex')}\`\`\``) } },
    { name: 'hexde', desc: 'Décode de l\'hexadécimal vers du texte normalisé.', usage: '.hexde <hex>', execute: async(ctx) => { if(!ctx.q) return await ctx.reply('Texte manquant'); await ctx.reply(`🔓 Texte: \n\`\`\`${Buffer.from(ctx.q, 'hex').toString('utf8')}\`\`\``) } },
    { name: 'bin2txt', desc: 'Convertit un code binaire lourd en texte lisible (ASCII).', usage: '.bin2txt <binaire>', execute: async(ctx) => { if(!ctx.q) return await ctx.reply('Texte manquant'); try { await ctx.reply(`🔓 Texte: \n\`\`\`${ctx.q.split(' ').map(bin => String.fromCharCode(parseInt(bin, 2))).join('')}\`\`\``) } catch(e){await ctx.reply('Erreur binaire')} } },
    { name: 'txt2bin', desc: 'Transforme n\'importe quelle phrase en code machine (binaire).', usage: '.txt2bin <texte>', execute: async(ctx) => { if(!ctx.q) return await ctx.reply('Texte manquant'); await ctx.reply(`🔐 Binaire: \n\`\`\`${ctx.q.split('').map(char => char.charCodeAt(0).toString(2).padStart(8, '0')).join(' ')}\`\`\``) } },
    { name: 'length', desc: 'Compte le nombre exact de caractères dans une chaîne.', usage: '.length <texte>', execute: async(ctx) => { if(!ctx.q) return await ctx.reply('Texte manquant'); await ctx.reply(`📏 Longueur: *${ctx.q.length}* caractères.`) } },
    { name: 'reverse', desc: 'Renverse complètement l\'ordre des lettres d\'une phrase.', usage: '.reverse <texte>', execute: async(ctx) => { if(!ctx.q) return await ctx.reply('Texte manquant'); await ctx.reply(`🔄 Inversé: \n${ctx.q.split('').reverse().join('')}`) } },
    { name: 'upper', desc: 'Passe un texte microscopique en MAJUSCULES ABSOLUES.', usage: '.upper <texte>', execute: async(ctx) => { if(!ctx.q) return await ctx.reply('Texte manquant'); await ctx.reply(`🔺 Majuscules: \n${ctx.q.toUpperCase()}`) } },
    { name: 'lower', desc: 'Convertit vos textes agressifs en douces minuscules.', usage: '.lower <texte>', execute: async(ctx) => { if(!ctx.q) return await ctx.reply('Texte manquant'); await ctx.reply(`🔻 Minuscules: \n${ctx.q.toLowerCase()}`) } },
    { name: 'titlecase', desc: 'Met une majuscule à La Première Lettre De Chaque Mot.', usage: '.titlecase <texte>', execute: async(ctx) => { if(!ctx.q) return await ctx.reply('Texte manquant'); await ctx.reply(`🔠 Titre: \n${ctx.q.split(' ').map(w => w[0]?.toUpperCase() + w.substr(1).toLowerCase()).join(' ')}`) } },
    { name: 'urlen', desc: 'Encode un texte pour le rendre utilisable dans une URL Web claire.', usage: '.urlen <texte>', execute: async(ctx) => { if(!ctx.q) return await ctx.reply('Texte manquant'); await ctx.reply(`🔗 URL Encode: \n\`\`\`${encodeURIComponent(ctx.q)}\`\`\``) } },
    { name: 'urlde', desc: 'Répare les liens URL encodés remplis de signes bizarres (%20).', usage: '.urlde <url>', execute: async(ctx) => { if(!ctx.q) return await ctx.reply('Texte manquant'); await ctx.reply(`🔗 URL Decode: \n\`\`\`${decodeURIComponent(ctx.q)}\`\`\``) } },
    { name: 'md5', desc: 'Génère un hash MD5 destructif et irréversible de votre texte.', usage: '.md5 <texte>', execute: async(ctx) => { if(!ctx.q) return await ctx.reply('Texte manquant'); await ctx.reply(`🔒 MD5: \n\`\`\`${crypto.createHash('md5').update(ctx.q).digest('hex')}\`\`\``) } },
    { name: 'sha1', desc: 'Sécurise votre phrase en un bloc SHA1 cryptographique de base.', usage: '.sha1 <texte>', execute: async(ctx) => { if(!ctx.q) return await ctx.reply('Texte manquant'); await ctx.reply(`🔒 SHA1: \n\`\`\`${crypto.createHash('sha1').update(ctx.q).digest('hex')}\`\`\``) } },
    { name: 'sha256', desc: 'Blindage militaire. Transforme un test en clé SHA-256 haute sécurité.', usage: '.sha256 <texte>', execute: async(ctx) => { if(!ctx.q) return await ctx.reply('Texte manquant'); await ctx.reply(`🔒 SHA256: \n\`\`\`${crypto.createHash('sha256').update(ctx.q).digest('hex')}\`\`\``) } },
    { name: 'uuidv4', desc: 'Génère instantanément un Identifiant Unique Universel (UUID v4) aléatoire.', usage: '.uuidv4', execute: async(ctx) => { await ctx.reply(`🆔 UUIDv4 Généré :\n\`\`\`${crypto.randomUUID()}\`\`\``) } },
    { name: 'passgen', desc: 'Forge un mot de passe blindé et cryptographique de la taille voulue.', usage: '.passgen [longueur]', execute: async(ctx) => { const len = parseInt(ctx.q) || 12; await ctx.reply(`🔑 Mdp: \n\`\`\`${crypto.randomBytes(Math.ceil(len/2)).toString('hex').slice(0, len)}\`\`\``) } },
    { name: 'randnum', desc: 'Génère un chiffre au hasard situé entre deux bornes que tu choisis.', usage: '.randnum [min] [max]', execute: async(ctx) => { const args = ctx.q.split(' '); const min = parseInt(args[0])||0; const max = parseInt(args[1])||100; await ctx.reply(`🎲 Aléatoire (${min}-${max}) :\n*${Math.floor(Math.random()*(max-min+1))+min}*`) } },
    { name: 'colorgen', desc: 'Crée un code couleur Hexadécimal 100% aléatoire pour les designers.', usage: '.colorgen', execute: async(ctx) => { const col = Math.floor(Math.random()*16777215).toString(16); await ctx.reply(`🎨 Couleur Générée : \n*#${col}*`) } },
    { name: 'wordcount', desc: 'Analyse un texte long et compte précisément le nombre de mots.', usage: '.wordcount <texte>', execute: async(ctx) => { if(!ctx.q) return await ctx.reply('Texte manquant'); await ctx.reply(`📝 Mots: *${ctx.q.split(/ +/).length}*`) } },
    { name: 'vowelcount', desc: 'Fouille une phrase pour compter uniquement le total de voyelles.', usage: '.vowelcount <texte>', execute: async(ctx) => { if(!ctx.q) return await ctx.reply('Texte manquant'); const c = (ctx.q.match(/[aeiouyàáâéèêëìíîïòóôöùúûü]/gi) || []).length; await ctx.reply(`🔤 Voyelles: *${c}*`) } },
    { name: 'consonantcount', desc: 'Disséque une phrase en comptant uniquement ses consonnes.', usage: '.consonantcount <texte>', execute: async(ctx) => { if(!ctx.q) return await ctx.reply('Texte manquant'); const c = (ctx.q.match(/[bcdfghjklmnpqrstvwxz]/gi) || []).length; await ctx.reply(`🔡 Consonnes: *${c}*`) } },
    { name: 'spacecount', desc: 'Énumère avec une précision chirurgicale le nombre d\'espaces tapés.', usage: '.spacecount <texte>', execute: async(ctx) => { if(!ctx.q) return await ctx.reply('Texte manquant'); const c = (ctx.q.match(/ /g) || []).length; await ctx.reply(`␣ Espaces: *${c}*`) } },
    { name: 'digitcount', desc: 'Analyse un texte pour extraire et compter uniquement les données chiffrées.', usage: '.digitcount <texte>', execute: async(ctx) => { if(!ctx.q) return await ctx.reply('Texte manquant'); const c = (ctx.q.match(/\d/g) || []).length; await ctx.reply(`🔢 Chiffres: *${c}*`) } }
];
